export class TemplateExampleConst {
    static RESPONSE_ERRORS = {
        ERROR_TEMPLATE_EXAMPLE_NOT_FOUND: 'ERROR_TEMPLATE_EXAMPLE_NOT_FOUND',
        ERROR_TEMPLATE_EXAMPLE_UPDATE_HAS_ERROR: 'ERROR_TEMPLATE_EXAMPLE_UPDATE_HAS_ERROR',
        ERROR_TEMPLATE_EXAMPLE_CREATE_HAS_ERROR: 'ERROR_TEMPLATE_EXAMPLE_CREATE_HAS_ERROR',
        ERROR_TEMPLATE_EXAMPLE_LANGUAGE_ALREADY_EXISTS: 'ERROR_TEMPLATE_EXAMPLE_LANGUAGE_ALREADY_EXISTS',
        ERROR_TEMPLATE_EXAMPLE_LANGUAGE_NOT_EXISTS: 'ERROR_TEMPLATE_EXAMPLE_LANGUAGE_NOT_EXISTS',
    };
    static RESPONSE_MESSAGE = {
    };
    static RESPONSE_VALIDATE = {
        ID_IS_REQUIRED: 'ID_IS_REQUIRED',
        ID_IS_NOT_VALID: 'ID_IS_NOT_VALID',
        TEMPLATE_EXAMPLE_DATA_1_IS_REQUIRED: 'TEMPLATE_EXAMPLE_DATA_1_IS_REQUIRED',
        TEMPLATE_EXAMPLE_DATA_1_IS_NOT_VALID: 'TEMPLATE_EXAMPLE_DATA_1_IS_NOT_VALID',
        TEMPLATE_EXAMPLE_DATA_2_IS_REQUIRED: 'TEMPLATE_EXAMPLE_DATA_1_IS_REQUIRED',
        TEMPLATE_EXAMPLE_DATA_2_IS_NOT_VALID: 'TEMPLATE_EXAMPLE_DATA_1_IS_NOT_VALID',
        TEMPLATE_EXAMPLE_DATA_3_IS_REQUIRED: 'TEMPLATE_EXAMPLE_DATA_1_IS_REQUIRED',
        TEMPLATE_EXAMPLE_DATA_3_IS_NOT_VALID: 'TEMPLATE_EXAMPLE_DATA_1_IS_NOT_VALID',
        TEMPLATE_EXAMPLE_DATA_4_IS_REQUIRED: 'TEMPLATE_EXAMPLE_DATA_4_IS_REQUIRED',
        TEMPLATE_EXAMPLE_DATA_4_IS_NOT_VALID: 'TEMPLATE_EXAMPLE_DATA_4_IS_NOT_VALID',
        LANGUAGE_IS_REQUIRED: 'LANGUAGE_MUST_BE_HAVE_DEFAULT_LANG',
        LANGUAGE_IS_NOT_VALID: 'LANGUAGE_IS_NOT_VALID',
        LANGUAGE_MUST_BE_HAVE_DEFAULT_LANG: 'LANGUAGE_MUST_BE_HAVE_DEFAULT_LANG',
        LANGUAGE_CAN_NOT_DUPLICATE: 'LANGUAGE_CAN_NOT_DUPLICATE',
        STATUS_IS_REQUIRED: 'STATUS_IS_REQUIRED',
        STATUS_IS_NOT_VALID: 'STATUS_IS_NOT_VALID'
    };
}