export class FolderConst {
    static RESPONSE_ERRORS = {
        ERROR_FOLDER_NOT_FOUND: 'ERROR_FOLDER_NOT_FOUND',
        ERROR_FOLDER_UPDATE_HAS_ERROR: 'ERROR_FOLDER_UPDATE_HAS_ERROR',
        ERROR_FOLDER_CREATE_HAS_ERROR: 'ERROR_FOLDER_CREATE_HAS_ERROR',
    };
    static RESPONSE_MESSAGE = {
    };
    static RESPONSE_VALIDATE = {
        ID_IS_REQUIRED: 'ID_IS_REQUIRED',
        ID_IS_NOT_VALID: 'ID_IS_NOT_VALID',
        NAME_IS_REQUIRED: 'NAME_IS_REQUIRED',
        NAME_IS_NOT_VALID: 'NAME_IS_NOT_VALID',
        STATUS_IS_REQUIRED: 'STATUS_IS_REQUIRED',
        STATUS_IS_NOT_VALID: 'STATUS_IS_NOT_VALID'
    };
}