export class ItemConst {
    static RESPONSE_ERRORS = {
        ERROR_ITEM_NOT_FOUND: 'ERROR_ITEM_NOT_FOUND',
        ERROR_ITEM_UPDATE_HAS_ERROR: 'ERROR_ITEM_UPDATE_HAS_ERROR',
        ERROR_ITEM_CREATE_HAS_ERROR: 'ERROR_ITEM_CREATE_HAS_ERROR',
    };
    static RESPONSE_MESSAGE = {
    };
    static RESPONSE_VALIDATE = {
        ID_IS_REQUIRED: 'ID_IS_REQUIRED',
        ID_IS_NOT_VALID: 'ID_IS_NOT_VALID',
        FOLDER_IS_REQUIRED: 'FOLDER_IS_REQUIRED',
        FOLDER_IS_NOT_VALID: 'FOLDER_IS_NOT_VALID',
        STATUS_IS_REQUIRED: 'STATUS_IS_REQUIRED',
        STATUS_IS_NOT_VALID: 'STATUS_IS_NOT_VALID'
    };
}